### ISSUE TITLE
Can run on alpine linux?

### ISSUE THREAD

**Issue by mathieupythian** [CISOfy/lynis#397] opened 2017-05-19 15:47 UTC
Trying to run on alpine linux, after cloning the GIT repo (since I cannot get it via the 'apk' package manager).

I get a bunch of errors when running "./lynis audit system".  Should it work?  Maybe I'm missing some dependencies?

```./lynis: line 112: locale: not found

[ Lynis 2.5.1 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2017, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################


[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           2.5.1
  Operating system:          Linux
  Operating system name:     Linux
  Operating system version:  4.9.27-moby
  Kernel version:            4.9.27
  Hardware platform:         x86_64
  Hostname:                  acf093929496
  ---------------------------------------------------
  Profiles:                  /usr/local/lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          /usr/local/lynis/plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Test category:             all
  Test group:                all
  ---------------------------------------------------
  - Program update status...                                  [ SKIPPED ]

[+] System Tools
------------------------------------
  - Scanning available tools...
  - Checking system binaries...
/usr/bin/wget: unrecognized option: V
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: wget [-csq] [-O FILE] [-Y on/off] [-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	-s	Spider mode - only check file existence
	-c	Continue retrieval of aborted transfer
	-q	Quiet
	-P DIR	Save to DIR (default .)
	-T SEC	Network read timeout is SEC seconds
	-O FILE	Save to FILE ('-' for stdout)
	-U STR	Use STR for User-Agent header
	-Y	Use proxy ('on' or 'off')

[+] Plugins (phase 1)
------------------------------------
 Note: plugins have more extensive tests and may take several minutes to complete
  
  - Plugin: pam
    [..]
  - Plugin: systemd
    [................]

[+] Boot and services
------------------------------------
  - Service Manager                                           [ UNKNOWN ]
  - Checking UEFI boot                                        [ DISABLED ]
    - Boot loader                                             [ NONE FOUND ]
  - Check startup files (permissions)                         [ OK ]

[+] Kernel
------------------------------------
  - Checking default runlevel                                 [ UNKNOWN ]
  - Checking CPU support (NX/PAE)
    CPU support: PAE and/or NoeXecute supported               [ FOUND ]
  - Checking kernel version and release                       [ DONE ]
  - Checking kernel type                                      [ DONE ]
  - Checking loaded kernel modules                            [ DONE ]
  - Checking Linux kernel configuration file                  [ FOUND ]
  - Check if reboot is needed                                 [ UNKNOWN ]

[+] Memory and Processes
------------------------------------
  - Checking /proc/meminfo                                    [ FOUND ]
  - Searching for dead/zombie processes                       [ OK ]
  - Searching for IO waiting processes                        [ OK ]

[+] Users, Groups and Authentication
------------------------------------
  - Administrator accounts                                    [ OK ]
  - Unique UIDs                                               [ OK ]
  - Unique group IDs                                          [ OK ]
  - Unique group names                                        [ OK ]
  - Query system users (non daemons)                          [ DONE ]
  - sudoers file                                              [ NOT FOUND ]
  - PAM password strength tools                               [ SUGGESTION ]
  - PAM configuration file (pam.conf)                         [ NOT FOUND ]
  - PAM configuration files (pam.d)                           [ NOT FOUND ]
  - PAM modules                                               [ NOT FOUND ]
  - Accounts without expire date                              [ OK ]
  - Accounts without password                                 [ OK ]
sed: bad regex '\?': Repetition not preceded by valid expression

Fatal error: Function ShowSymlinkPath() called without a file name```

**Comment by mboelen** [comment] 2017-05-23 13:06
Looks like some of the issues are caused by busybox replacing 'normal' binaries.

Can you show what the latest test was being executed? You can see this by looking at /var/log/lynis.log or /tmp/lynis.log, and scroll to the bottom.

**Comment by mathieupythian** [comment] 2017-05-23 13:36
Here are the last lines of the /var/log/lynis.log file:

```
2017-05-19 16:02:23 Performing test ID AUTH-9288 (Checking for expired passwords)
2017-05-19 16:02:23 Test: check if we can access /etc/shadow (escaped: )
2017-05-19 16:02:23 PID file removed (/var/run/lynis.pid)
2017-05-19 16:02:23 Temporary files:  /tmp/lynis.XXXXgohOEE
2017-05-19 16:02:23 Action: removing temporary file /tmp/lynis.XXXXgohOEE
2017-05-19 16:02:23 Lynis ended with exit code 1.
```

**Comment by mboelen** [comment] 2017-06-21 12:55
Can you run the following command: `echo "/etc/shadow" | sed 's/\*/\\*/; s/\?/\\?/'`

Does it give any output? Works for me on Linux, so might need some testing.

**Comment by vannhi** [comment] 2017-06-21 18:37
I'm interessed in this problem as well.

@mboelen it give that:

> sed: bad regex '\?': Repetition not preceded by valid expression

it give output `/etc/shadow` if update to 4.4-r0

**Comment by mboelen** [comment] 2017-06-21 18:55
Is sed a dedicated binary on Alpine or part of busybox?

**Comment by vannhi** [comment] 2017-06-21 19:30
For version 4.4-r0, it depends on busybox and musl: https://pkgs.alpinelinux.org/package/v3.6/main/x86/sed

**Comment by mboelen** [comment] 2018-01-20 16:37
@mathieupythian what output do you get now with a newer version of Lynis? Several changes have been made in the last months to better support busybox and other tools.

**Comment by vannhi** [comment] 2018-01-20 20:32
Work fine for me with lynis 2.5.7, no need to update sed as I did with lynis 2.5.1

**Comment by mboelen** [comment] 2018-01-21 11:25
Thanks @vannhi - Closing this issue.

**Closed by mboelen** 2018-01-21 11:25 UTC
