### ISSUE TITLE
Exceptions in GetHostID

### ISSUE THREAD

**Issue by Vogtinator** [CISOfy/lynis#1183] opened 2021-07-05 11:53 UTC
**Describe the bug**
After upgrading Lynis to 3.0.5, it fails to generate a Host ID.

**Version**
 - openSUSE Tumbleweed
 - Lynis 3.0.5

**Expected behavior**
HostID is generated

**Output**
```
  Function/test:  [GetHostID]
  Message:        Can't create hostid (no MAC addresses found)
...
  Function/test:  [GetHostID]
  Message:        Can't create HOSTID, command ip not found
```

**Additional context**
The network interface is called `ens4`, but the `ip -family link addr show up label 'en*'` command does not show anything.

The `command ip not found` message in the second exception seems to be wrong?

**Comment by silentcreek** [comment] 2021-07-06 20:56
I can confirm this issue. Happens to me on Debian 10 as well. The network interface is called eno1 and `ip -family link addr show up label 'en*'` doesn't show anything. If I remove the `label 'en*'` at the end, ip will show the interface. So that syntax is wrong.

But what's more is that I also think, that the wildcard itself is wrong or not the best way to go. I have a different machine, a firewall/gateway, which has different interface names such as lan1, lan2 and so on. So, even if the syntax itself gets fixed, the wildcard wouldn't match the interface names on that machine.

I haven't yet found a way to limit the output of the ip command to just ethernet interfaces. I'm still looking into ways to figure that out via the entries in /sys/class/net/$(interface_name)/*. So far, I only found that wireless interfaces have a subdirectory wireless in there, but I'll see if there is a better way to determine this. 

I'm also wondering, however, why the output should be limited to ethernet interfaces at all? Why not just use the first interface regardless of whether it's wireless or not?

**Comment by Vogtinator** [comment] 2021-07-07 06:40
> But what's more is that I also think, that the wildcard itself is wrong or not the best way to go.

Using the device of the default route instead might work.

**Comment by silentcreek** [comment] 2021-07-07 07:36
> > But what's more is that I also think, that the wildcard itself is wrong or not the best way to go.
> 
> Using the device of the default route instead might work.

Hmm, you'd still need a fallback solution because the device with the default gateway might be a ppp device without a MAC address. This happens to be the case on my firewall/gateway. The default gateway is ppp0 and it doesn't have a MAC address that could be used for the hostid generation.

**Comment by NRGLine4Sec** [comment] 2021-07-07 08:51
Maybe this command could help you :
```bash
pci=`lspci  | awk '/Ethernet/{print $1}'`; find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -v pciid=$pci -F\/ '{if($0 ~ pciid){print $NF}}'
```
or this command to get the interface used by the first default route :
```bash
awk 'NR==1,/default/ {print $5}' <(ip route)
```

**Comment by silentcreek** [comment] 2021-07-07 09:30
> Maybe this command could help you :
> 
> ```shell
> pci=`lspci  | awk '/Ethernet/{print $1}'`; find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -v pciid=$pci -F\/ '{if($0 ~ pciid){print $NF}}'
> ```

lspci is not universally available. I have a machine running a minimal Debian installation that does not have lspci. And I'd assume there are even more stripped down distributions for containers and such, that don't ship lspci by default.
In addition, not all ethernet interfaces are connected via PCI.

> or this command to get the interface used by the first default route :
> 
> ```shell
> awk 'NR==1,/default/ {print $5}' <(ip route)
> ``

See above, not all interfaces have MAC addresses even though they might be the default interface or route.

**Comment by NRGLine4Sec** [comment] 2021-07-07 09:55
OK, so maybe with this :
```bash
find /sys/class/net ! -type d | xargs --max-args=1 realpath | awk -F'/' '!/virtual/ {if($8){print $8}}'
```
But with this command, you will get ethernet and wifi interface name as result.

**Comment by silentcreek** [comment] 2021-07-08 01:05
Ok, I have given this some more thought and testing. It seems that determining the interface type isn't as trivial, at least not without additional tools that might be unavailable. SUSE folks have written a shell function to determine the interface type based on sysfs properties. This seems quite helpful and thorough, see: https://github.com/openSUSE/sysconfig/blob/88c7a0f3018755b4eca0a3f573f05a7218860f36/scripts/functions#L282

@mboelen Based on this, I'm proposing the following solution to determine the MAC address:
`FIND="$(cd /sys/class/net ; for _if in * ; do egrep -sq '^(1|24)$' "$_if/type" && [ ! -d "/sys/devices/virtual/net/$_if" ] && grep -s : "$_if/address" ; done | head -n1)"`

This will print out the MAC address of the first wired or wireless interface (in alphabetical order). The rationale is this:
1) Don't bother excluding wireless interfaces. You may run Lynis on a laptop that doesn't have a wired interface.
2) Don't bother filtering interfaces that are not up. Maybe you're running Lynis while your connection is down temporarily.
3) Use the alphabetical order. In most setups this ensures that wired interfaces have priority over wireless interfaces. In addition, since most distributions today use persistent interface names, the order will be more or less stable unless you add or remove interfaces. The POSIX standard defines that the wildcard in the for loop is expanded in alphabetical order (and the bash manual says the same). I have tested this in three different shells and it seems to hold true.
4) I included interface type 24 (Firewire-based ethernet) in the test. I assume this will be rather uncommon today, but it doesn't hurt to include it either.
5) I verified that all the other interface classes that are listed as type 1 in SUSE's function (bridge, bond, vlan, etc.) also appear under /sys/devices/virtual/net/ so it is enough to exclude those to ensure only wired and wireless interfaces are left.
6) This implementation also avoids using options of the ip command that might not be universally available. I found that busybox's implementation of the ip command is quite limited and doesn't offer some of the extensions that might have helped otherwise in this case.

What do you think? Should I write a small patch or are there any objections or ways to improve this further?


@NRGLine4Sec Your second command prints "net" in addition to the interface name, btw.

**Comment by mboelen** [comment] 2021-07-08 11:45
Thanks @Vogtinator for reporting

Thanks @NRGLine4Sec and @silentcreek for your research, this definitely helps in getting a more stable method to generate a unique set of identifiers. I do have a few additions, some are based on assumptions and the rationale behind writing the function in the first place. So let me elaborate:

- We want to have the function generate the same identifiers on a system, as reliable as possible. Ideally, we want it to return the same values each time when you execute the function.
- Interfaces that are always up and configured are more reliable than wireless or interfaces that are down, therefore the last category is something that we rather skip in the first place. Note that there is always the fallback to generate host identifiers manually in case a system is "unstable" when it comes to its identifiers.

Although using /sys is a great option, it is not available for non-privileged users, while the output of `ip` is. Still, it makes sense to add it as a backup when one is a privileged user.

I just made some changes, including improved the logging. If you have the chance, please test and see if this resolves the error.

**Comment by Vogtinator** [comment] 2021-07-08 12:06
> I just made some changes, including improved the logging. If you have the chance, please test and see if this resolves the error.

I gave it a try: The error messages are gone, but the test for `en*` is not working:

```2021-07-08 13:20:29 Info: selecting interfaces by label 'en*' did not return results, trying without it```

but

```
localhost:~ # ip -family link a s up
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:2b:c8:a1 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
```

**Comment by silentcreek** [comment] 2021-07-08 12:17
> * We want to have the function generate the same identifiers on a system, as reliable as possible. Ideally, we want it to return the same values each time when you execute the function.

But isn't the link state way more volatile than the interfaces? On all my machines, the interface names and their mac addresses are persistent. But the the link state may be down temporarily. So, depending on the link state does not increase the likelyhood of consistent results.

If I had to prioritze certain interfaces for the sake of consitency, I would try to give the lowest preference to devices that are attached externally (USB), since they are more likely to come and go compared to internal interfaces.

> Although using /sys is a great option, it is not available for non-privileged users, while the output of `ip` is. Still, it makes sense to add it as a backup when one is a privileged user.

Really? On all the distributions I use, /sys or /sys/class/net is by default readable by any user. Hence, I would suggest not to limit the fallback option of reading from /sys to priviledged users generally but simply check whether the entries are readable.

> I just made some changes, including improved the logging. If you have the chance, please test and see if this resolves the error.

I will test this later. Thanks.

**Comment by silentcreek** [comment] 2021-07-08 12:22
> I gave it a try: The error messages are gone, but the test for `en*` is not working:

Yes, as mentioned before, the syntax for the wildcard match
`ip -family link addr show up label 'en*'`
does not work on any of my machines (mostly Debian and OpenSUSE).

**Comment by mboelen** [comment] 2021-07-08 13:13
`Really? On all the distributions I use, /sys or /sys/class/net is by default readable by any user. Hence, I would suggest not to limit the fallback option of reading from /sys to priviledged users generally but simply check whether the entries are readable.`

Tested again and indeed, it does work. Got an error earlier stating that access was denied. Switched things, so that `ip` is the second in order.

I'm the first to admit that there are multiple ways to define what is reliable when it comes to interfaces. Still, we have to pick some method and keep it as stable as possible. So for now interfaces that are marked 'UP' are considered more important than those that are down. Especially systems that are 24/7 up will usually have a dedicated configuration with stable interfaces. For desktops/notebooks, it may change. If one has troubles with these systems to get the same host identifiers each time, then there is the `lynis generate hostids --save` option to make them sticky.

I have seen the note regarding the 'label' function not working. Will make an extra change for that. Looks like more modern versions of `ip` don't work, while older ones do. Lynis development is tested on purpose on a somewhat older system to avoid having too new tools that are not always available.

**Comment by mboelen** [comment] 2021-07-08 13:20
Created change https://github.com/CISOfy/lynis/commit/78677597503279d941693b5fd2adcf9e95ae05f7

With the errors gone, closing this issue. Thanks again for your input and thoughts!

**Closed by mboelen** 2021-07-08 13:20 UTC
Labels: bug

**Comment by madindehead** [comment] 2021-07-10 15:08
Coming here from #1181 

I cloned the repo onto a VM running Ubuntu Server 20.04.2. Still seeing them same issue when I run Lynis using ./lynis audit system, but that is more likely to be user error than the code not working. 

Is it just a case of cloning the repo and running? Or is there anything I need to do to get it working with the fix? Thanks.

**Comment by silentcreek** [comment] 2021-07-10 21:44
> I cloned the repo onto a VM running Ubuntu Server 20.04.2. Still seeing them same issue when I run Lynis using ./lynis audit system, but that is more likely to be user error than the code not working.
> 
> Is it just a case of cloning the repo and running? Or is there anything I need to do to get it working with the fix? Thanks.

If you already have lynis installed via apt/dpkg, then you need to use the command line argument `--usecwd` like so:
`./lynis --usecwd audit system`
This is because, by default, lynis prefers the install locations of its functions/test over the current working directory. So, even if you cloned the latest code from the repository, it will still use old code installed by your package manager unless you use the `--usecwd` option.

Nevertheless, I tested the code myself now and even though the exceptions are gone now, there is still a syntax error in the code at:
https://github.com/CISOfy/lynis/blob/78677597503279d941693b5fd2adcf9e95ae05f7/include/functions#L994
@mboelen 
I think the if clause should simply be
`if [ -d /sys/class/net ]; then`
because in addition to the missing opening square bracket, $FIND will always be empty at this stage.

**Comment by mboelen** [comment] 2021-07-12 13:54
Thanks @silentcreek - Made the change.
