### ISSUE TITLE
lynis making incorrect assumption about tls_certificate and tls_privatekey for exim4

### ISSUE THREAD

**Issue by imthenachoman** [CISOfy/lynis#656] opened 2019-03-15 02:22 UTC
**Describe the bug**
When I run a system audit I see this:

    [+] Software: e-mail and messaging
    ------------------------------------
      - Exim status                                               [ RUNNING ]
        - Type                                                    [ SATELLITE ]
        - Certificate not set                                     [ WARNING ]
        - Private Key not set                                     [ WARNING ]

I have configured exim4 to send e-mails using TLS through `smtp.gmail.com::465` , **NOT** STARTTLS through `smtp.gmail.com::587`.

I don't really completely understand how exim4 works but I posted about this at https://serverfault.com/questions/958170/exim4-showing-tls-certificate-and-tls-privatekey-not-set-when-configured-to-send and based on the 3rd comment I think maybe Lynis is making an incorrect assumption.

[wurtel](https://serverfault.com/users/241548/wurtel) said 
> Only if those parameters are specifically configured for the `remote_smtp_smarthost` entry for transports. That almost never happens and the tls stuff is configured in the main config part and inherited by the transports. It looks like Lynis is making assumptions about your configuration.

I did a test and exim's log **does** show the e-mail being sent using TLS:

>     2019-03-14 22:10:56 1z32JE-01011x-1a => username@gmail.com <username@hostname.lan> R=smarthost T=remote_smtp_smarthost H=gmail-smtp-msa.l.google.com [173.194.207.109] X=TLS1.2:ECDHE_RSA_CHACHA20_POLY1305:256 CV=no DN="C=US,ST=California,L=Mountain View,O=Google LLC,CN=smtp.gmail.com" A=plain C="250 2.0.0 OK  1512345856 r17sm134499qkm.17 - gsmtp"
>     2019-03-14 22:10:56 1z32JE-01011x-1a Completed

**Version**
 - Debian 9
 - Lynis 2.7.2

**Expected behavior**
Not sure?

**Output**
Added above.

**Additional context**
N/A

**Comment by mboelen** [comment] 2019-03-15 13:21
Can you show your full configuration file, so we can see what we can adjust?

**Comment by imthenachoman** [comment] 2019-03-15 13:55
I assume you mean the full configuration file for exim? Do you just want `/etc/exim4/exim4.conf.template` or any other files too?

**Comment by dvehrs** [comment] 2019-05-23 21:39
Excuse me for jumping in but I may be able to help. 

This does appear to be a bug in the way the Exim configuration is parsed.

Good explanation on why this is happening:  https://security.stackexchange.com/questions/161924/why-does-gmail-add-accounts-using-smtp-server-recommend-ssl-instead-of-tls

To make a long story short when you use port 465 after a connection is made, it negotiates whether to use SSL or TLS.  So that explains why you see TLS in your exim logs but it did not require that certificates be installed in advance.

Rather than see the configuration file, what is being tested for these items is the output of:
  exim -bP transport remote_smtp_smarthost

So if you can submit that (after reviewing it for any private information you'd rather not share) then we may be able to determine a way to differentiate between the configurations.

**Comment by dvehrs** [comment] 2019-05-23 22:24
I may have misspoken in my last comment.  After reviewing how the Exim configuration is parsed, the bug may not be in it but rather may reside in how it is presenting what it finds to the user.  The issue may be caused by the use of STATUS_WARNING when it is determined that the certificate and private key options are not set.

**Comment by dvehrs** [comment] 2019-05-24 14:20
I've been thinking about this overnight and its probably worth explaining why we are looking for the certificates.  

In this case, the certificates are used for mutual authentication.  However because the configuration for this is done partially on the client and partially on the server, it is difficult for Lynis to test for.  Any test we use will be dealing with having partial information.

Example of the configuration for mutual authentication: https://github.com/Exim/exim/wiki/AuthenticatedSmtpUsingCert

Mutual authentication is a good thing if you're managing a few servers and want to aggregate all the email through one smarthost.    It is a completely different issue for a service like Gmail.  It would be very challenging for them to get certificates from every client machine and tie them to the correct accounts.  

The question before us is how do we distinguish between the two valid configurations?  I've submitted a pull request that adds testing to determine if tls_try_verify_hosts and tls_verify_hosts are enabled but I placed these tests at the tail end of the exim configuration tests.  Maybe they should come sooner....

**Comment by imthenachoman** [comment] 2019-06-01 19:24
This is great information. Thank you! My server is down for a while. I will provide those logs as soon as I get it back up.

**Comment by mboelen** [comment] 2019-09-10 14:37
Hi @imthenachoman - is your issue resolved in the meantime with the work that @dvehrs did?

**Comment by imthenachoman** [comment] 2019-09-11 01:37
@mboelen I've had some personal matters come up so I haven't had a chance to follow up. Feel free to close this issue and if needed I can re-open or submit a new one later. Sorry for the trouble!

**Comment by mboelen** [comment] 2019-09-11 06:10
Ok, will close for now.

**Closed by mboelen** 2019-09-11 06:10 UTC

**Comment by dvehrs** [comment] 2019-09-11 17:01
Sorry to jump in a bit late but I don't think my earlier work would have resolved this issue.  I've submitted a pull request for a small change that will.  It's certainly not the final way to address this issue but it's probably a way we can move forward without causing users undue concern.

Dave

**Comment by mboelen** [comment] 2019-09-11 17:49
That's ok @dvehrs - let's do it in small steps. In the meantime, I'm cleaning up the queue and old issues, so new contributions get full attention again.
