### ISSUE TITLE
Status unknown in update info on fresh install on Debian 9.8

### ISSUE THREAD

**Issue by imthenachoman** [CISOfy/lynis#642] opened 2019-02-16 20:46 UTC
**Describe the bug**
`lynis update info` shows `Unknown` status.

**Version**
 - Debian 9.8
 - Lynis version 2.7.1

**Expected behavior**
Not sure exactly but I assume it should say status okay or something.

**Output**
    $ sudo lynis update info
    
     == Lynis ==
    
      Version            : 2.7.1
      Status             : Unknown
      Release date       : 2019-01-31
      Update location    : https://cisofy.com/lynis/
    
    
    2007-2019, CISOfy - https://cisofy.com/lynis/

**Additional context**
N/A

**Comment by mboelen** [comment] 2019-03-04 15:14
Thanks for reporting. In this case, your system simply can't determine the latest version. Most likely because of the system not having the `dig` or `host` utility.

Will close this issue, as it is not a bug.

**Closed by mboelen** 2019-03-04 15:14 UTC

**Comment by imthenachoman** [comment] 2019-03-04 22:25
Got it. Thanks!
