### ISSUE TITLE
lynis show commands returns tr: misaligned [:upper:] and/or [:lower:] construct error

### ISSUE THREAD

**Issue by bugzpai** [CISOfy/lynis#527] opened 2018-02-27 00:04 UTC
Hi,
Have ubuntu 16.04.4 LTS and installing Lynis following instructions as indicated by [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-perform-security-audits-with-lynis-on-ubuntu-16-04). Installed Lynis 2.6.2-100. When I run` lynis show commands`, the system returns with: 
```
tr: misaligned [:upper:] and/or [:lower:] construct

Commands:
lynis audit
lynis configure
lynis show
lynis update
lynis upload-only
```

I notice that the tr: misaligned message has been cited for other software -
 [fairly legacy error](https://github.com/ib-controller/ib-controller/issues/117). Did not see it with relation to lynis, though, so wondering if this is my system or the software which is the reason why the message is showing up? Should I worry about it? If so, are there any fixes for it?

**Comment by mboelen** [comment] 2018-02-28 17:56
On our test system with Ubuntu 16.04 LTS, this does not happen.

I guess you get this output also when running Lynis, or possibly other similar messages?

**Comment by mboelen** [comment] 2018-03-05 10:18
@bugzpai ?

**Comment by mboelen** [comment] 2018-03-08 16:31
Closing issue for now, as we can't reproduce it.

**Closed by mboelen** 2018-03-08 16:31 UTC
Labels: information-needed
