### ISSUE TITLE
Systemd hang/stuck whatever

### ISSUE THREAD

**Issue by Webdrian** [CISOfy/lynis#1432] opened 2023-08-12 01:51 UTC
**Describe the bug**
I just installed Lynis via Git and run `sudo ./lynis audit system` they always stuck on systemd (PLGN-3814)
<img width="658" alt="CleanShot 2023-08-12 at 03 48 23@2x" src="https://github.com/CISOfy/lynis/assets/89680380/e446abca-a19f-4f56-b1a3-680dd3a8ecab">
<img width="694" alt="CleanShot 2023-08-12 at 03 48 14@2x" src="https://github.com/CISOfy/lynis/assets/89680380/e7d624a5-ea65-49ec-a2e0-bf7f7e82d210">

If i install via package `sudo apt-get install lynis -y` and run `sudo lynis audit system` they run pretty good! But the Version is 3.0.7 and its outdated?

What i have to do now?

**Version**
 - Distribution [e.g. Ubuntu 22.04]
 - Lynis version [e.g. 3.0.9]

**Expected behavior**

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

**Comment by halfluke** [comment] 2023-09-12 14:55
I've just had the same issue and I fixed it this way:
copy default.prf to custom.prf
add the following line in custom.prf under # Skip a test (one per line)
skip-test=PLGN-3814

Reference: https://adamtheautomator.com/lynis/

**Comment by Huaba** [comment] 2023-11-07 13:34
We scan about 40 servers with Lynis over a Gitlab Pipeline. One server had the same issue, all others run perfect.

What i've found:
- only the output hang in "plugin: systemd"
- if i track `lynis.log` with a `tail -f` it hangs on `Performing test ID PLGN-3814 (Verify journal integrity)` - if I wait a long time, nothing happens - if I then press CTRL-C and finish the `tail -f`, it scrolls to the end of the log and shows that it is finished.
- the scan finishes without problems in the background (see it in `lynis.log` with `Lynis ended successfully.` as last entry

Lynis version 3.0.9
OS: Ubuntu 22.04

**Comment by mboelen** [comment] 2024-03-18 09:30
> I've just had the same issue and I fixed it this way: copy default.prf to custom.prf add the following line in custom.prf under # Skip a test (one per line) skip-test=PLGN-3814
> 
> Reference: https://adamtheautomator.com/lynis/

Please don't copy the default.prf to custom.prf, but only add the differences to the latter one.

**Comment by mboelen** [comment] 2024-03-18 09:35
The issue shared by @Webdrian is often caused by huge journal files or even errors in its internal database structure. Something that we can't pick up from Lynis, as we simply query some commands and check their output. If a command hangs or takes a long while to complete, Lynis will simply wait for the command execution.

My suggestions:

- Run the command from this test manually and see what happens. Try to see if you can get a more verbose output
- Disable this particular plugin if it keeps failing (add it to your custom.prf, see default.prf for the structure on disabling a test)

So with no change that can be made (yet) to Lynis, I will close this issue.

**Closed by mboelen** 2024-03-18 09:35 UTC
Labels: no-change
