### ISSUE TITLE
lynis installation fails on Debian 11 due to an  unsupported compression

### ISSUE THREAD

**Issue by afunix** [CISOfy/lynis#1461] opened 2024-03-11 16:30 UTC
**Describe the bug**
During the recent attempt to upgrade lynis all of my Debian 11s ended up not being able to install lynis package:
```
dpkg-deb: error: archive '/var/cache/apt/archives/lynis_3.1.0-100_all.deb' uses unknown compression for member 'control.tar.zst', giving up
```

**Version**
 - Debian 11.8
 - 3.1.0-100

**Expected behavior**
Package can be installed.

**Output**
```
dpkg-deb: error: archive '/var/cache/apt/archives/lynis_3.1.0-100_all.deb' uses unknown compression for member 'control.tar.zst', giving up
```

**Additional context**
Debian 11 LTS is supported till end of June 2026.

Lynis is installed from deb repo:
```
# cat /etc/apt/sources.list.d/cisofy-lynis.list 
deb https://packages.cisofy.com/community/lynis/deb/ stable main
```

```
# # cat /etc/debian_version 
11.8
```

**Comment by mboelen** [comment] 2024-03-11 17:22
Thanks for reporting. Looks like ZSTD compression is not supported yet on Debian 11. We already made a chance in the background to enforce GZIP compression instead. Will have to look in the upcoming day if we will release a new version or refresh the package.

**Comment by bcutter** [comment] 2024-03-12 18:45
Same here on hosts with Debian < 12 (one Debian 10, one Debian 11, ...).

I was thinking of forcing the update using this...
https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg/745467#745467
...but luckily found this issue and will instead wait for a refactored package.

**Comment by bcutter** [comment] 2024-03-16 23:08
@mboelen can you give us a brief update please? I still can not update. Can you confirm packages have been refreshed?

**Comment by mboelen** [comment] 2024-03-17 10:44
New release is available. Is the issue fixed for you? @afunix @bcutter

**Comment by bcutter** [comment] 2024-03-17 12:09
3.1.1 confirmed installed for one host, awaiting confirmation for another one (scheduled upgrades). I think it's good now.

**Comment by mboelen** [comment] 2024-03-17 12:13
Thanks. Will close this issue then. If something still fails for some reason, please let it know.

**Closed by mboelen** 2024-03-17 12:13 UTC
Labels: enhancement

**Comment by afunix** [comment] 2024-03-17 17:03
I can confirm I'm able to install lynis from the repo on Debian 11.
However I don't think this is an enhancement. The functionality was broken, so I believe this should be a bugfix.

**Comment by mboelen** [comment] 2024-03-17 18:56
> I can confirm I'm able to install lynis from the repo on Debian 11. However I don't think this is an enhancement. The functionality was broken, so I believe this should be a bugfix.

Changed
