### ISSUE TITLE
Improper way of finding binaries

### ISSUE THREAD

**Issue by BlessJah** [CISOfy/lynis#469] opened 2017-10-04 18:06 UTC
Binaries are found by looping over all of the files in the (predefined) list of directories, and comparing (in `case` loop) to list of desired binaries. Checking if a path represents a file (`if [ -f ${BINARY} ] ; ...`) is done only for some binaries.

This approach may led to some errors (e.g. filename containing space, path pointing to a directory instead of file, path pointing to non-executable file).

I think we should use `command -v` to adress this issue and #468.
- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html#tag_20_22

https://github.com/CISOfy/lynis/blob/master/include/binaries#L81
```sh
                        case ${FILENAME} in
                            aa-status)              APPARMORFOUND=1;       AASTATUSBINARY=${BINARY};                                                      LogText "  Found known binary: aa-status (apparmor component) - ${BINARY}"                                ;;
                            afick.pl)               AFICKFOUND=1;          AFICKBINARY=${BINARY};                                                         LogText "  Found known binary: afick (file integrity checker) - ${BINARY}"                                ;;
                            aide)                   AIDEFOUND=1;           AIDEBINARY=${BINARY};                                                          LogText "  Found known binary: aide (file integrity checker) - ${BINARY}"                                 ;;
                            apache2)                if [ -f ${BINARY} ]; then HTTPDFOUND=1;          HTTPDBINARY=${BINARY};                               LogText "  Found known binary: apache2 (web server) - ${BINARY}";                                      fi ;;
```

**Comment by mboelen** [comment] 2017-10-06 12:51
Hi @BlessJah - Thanks for your guidance and tips. Before we change this, we need to make sure that it properly works. Unfortunately sometimes changes that "make sense" do actually not work on all platforms. Do you have besides a Linux system some other platforms to test? Then I happily look together with you to see if these changes work as intended.

**Comment by BlessJah** [comment] 2017-10-07 17:44
Which systems are usually tested? I can check the `command` behavior on *FreeBSD* and *MacOS* on Monday.

*FreeBSD*, *OpenBSD*, *NetBSD* and Oracle *Solaris* manuals describe `command` behavior. Both *AIX* and *HP-UX* are POSIX Certified (according to Wikipedia).

- https://www.freebsd.org/cgi/man.cgi?query=sh&sektion=&n=1
- https://man.openbsd.org/sh.1
- http://netbsd.gw.com/cgi-bin/man-cgi?sh++NetBSD-7.1
- https://docs.oracle.com/cd/E26502_01/html/E29030/command-1.html
- https://en.wikipedia.org/wiki/POSIX#POSIX-certified

**Comment by majormoses** [comment] 2018-01-12 04:46
From what I have read this should be good with any POSIX compliant systems though I have not tested all of them.

**Comment by mboelen** [comment] 2018-01-25 12:16
Thanks for the links and sharing your thoughts @BlessJah and @majormoses 

We performed additional research:
* One of the mentioned issues (a binary might be directory), can easily be resolved by filtering out directories. The related [ -f xyz ] entries are removed.
* Spaces in names are an issue, but typically not for binaries. So missing a file when scanning for binaries is an accepted risk.
* Dead symlinks might happen and is an acceptable risk. This happens not that often, and can easily be spotted and resolved by the system owner.

For now, we will leave thing as-is. That means: the existing routines are optimized further now since opening this issue. Also, in this way they have the best performance of the options we could find.

Thanks!

**Closed by mboelen** 2018-01-25 12:16 UTC

**Comment by AlainG80** [comment] 2018-01-28 10:19
In my AIX /bin/sh is actually linked to /bin/ksh and they do support the command utility.

**Comment by mboelen** [comment] 2018-01-28 11:09
Thanks @AlainG80 - that is good to know for future adjustments to the related routines.
