### ISSUE TITLE
Default.prf file fails with unknown option "compresseduploads"

### ISSUE THREAD

**Issue by ken-ie** [CISOfy/lynis#744] opened 2019-08-14 14:28 UTC
**Describe the bug**
After a fresh clone of Lynis, running Lynis fails with with the following error:
```
[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]

  [WARNING]: Your profile '/lynis/default.prf' contains unexpected characters. See the log file for more information.


Error: found one or more errors in profile /lynis/default.prf


Full line: compresseduploads=yes
Details: Unknown option 'compresseduploads' found (with value: yes)

```

**To Duplicate**
```
docker run -d --name tmp-container --entrypoint=tail alpine -F junk
docker exec -t tmp-container apk update
docker exec -t tmp-container apk add git
docker exec -t --workdir=/lynis --env LANGUAGE=en --env LANG=en --env _=none tmp-container ./lynis audit system --no-colors
```

**Version**
 - Distribution: Alpine docker container, `latest`
 - Lynis version: 3.0.0

**Expected behavior**

**Output**
```
2019-08-14 14:22:32 Starting Lynis 3.0.0 with PID 36, build date 2019-07-14
2019-08-14 14:22:32 ===---------------------------------------------------------------===
2019-08-14 14:22:32 ### 2007-2019, CISOfy - https://cisofy.com/lynis/ ###
2019-08-14 14:22:32 Checking permissions of /lynis/include/profiles
2019-08-14 14:22:32 File permissions are OK
2019-08-14 14:22:32 Reading profile/configuration /lynis/default.prf
2019-08-14 14:22:32 Found unexpected or possibly harmful characters in the profile. See output below.
2019-08-14 14:22:32 Output:    -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   - CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md CONTRIBUTORS.md FAQ INSTALL LICENSE README README.md SECURITY.md db default.prf developer.prf extras include lynis lynis.8 plugins    -   -   -   -   -   -   -
2019-08-14 14:23:02 Action: created temporary file /tmp/lynis.XXXXGNenkI
2019-08-14 14:23:02 Unknown option compresseduploads (with value: yes)
2019-08-14 14:23:02 PID file removed (/var/run/lynis.pid)
2019-08-14 14:23:02 Temporary files:  /tmp/lynis.XXXXGNenkI
2019-08-14 14:23:02 Action: removing temporary file /tmp/lynis.XXXXGNenkI
2019-08-14 14:23:02 Lynis ended with exit code 1.
```
**Additional context**

**Comment by ken-ie** [comment] 2019-08-14 15:34
It appears that the `-` is being removed during processing of the default.prf file. 
Commenting out `compressed-uploads` from the default.prf file causes the follow error:
```
[WARNING]: Your profile '/lynis/default.prf' contains unexpected characters. See the log file for more information.


Error: found one or more errors in profile /lynis/default.prf


Full line: erroronwarnings=no
```

**Comment by mboelen** [comment] 2019-08-19 10:48
Can't reproduce, as the last command gives me 

> OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/lynis\") set in config.json failed: no such file or directory": unknown

Something missing in the commands, like a directory creation that you do?

**Comment by ken-ie** [comment] 2019-08-19 13:43
*facepalm* I didn't include the instruction to clone the repo.

Lets try again...
```
docker run -d --name tmp-container --entrypoint=tail alpine -F junk
docker exec -t tmp-container apk update
docker exec -t tmp-container apk add git
docker exec -t tmp-container git clone https://github.com/CISOfy/lynis
docker exec -t --workdir=/lynis --env LANGUAGE=en --env LANG=en --env _=none tmp-container ./lynis audit system --no-colors
```

When finished
`docker kill tmp-container`

**Comment by daniejstriata** [comment] 2019-08-20 13:21
Does the prf reference RUNDIR by any chance? I used that in all my prfs and since version 3 it causes an error. If not related let me know so I can log a new issue.
```
[+] Initializing program
------------------------------------
- Detecting OS...  [ DONE ]
  [WARNING]: Your profile '/opt/lynis/server-redhat.prf' contains unexpected characters. See the log file for more information.
```

**Comment by mboelen** [comment] 2019-08-20 14:03
Thanks, that makes more sense :)

I applied several commits to improve execution. Does it work properly for you now?

Commits:
https://github.com/CISOfy/lynis/commit/a310c43176e22815722608c8dc3e6cd5a42bc091
https://github.com/CISOfy/lynis/commit/e7d6aaa44dd8189cab5d0d001c93864b1ecb0005

**Comment by mboelen** [comment] 2019-08-21 12:09
Tested on a Docker instance, and looks to be working. Closing this issue. Feel free to respond in case you got another result on your system.

**Closed by mboelen** 2019-08-21 12:09 UTC
