### ISSUE TITLE
-Q (--quick) argument ignored.

### ISSUE THREAD

**Issue by Achaean** [CISOfy/lynis#1290] opened 2022-05-03 18:43 UTC
Adding the -Q argument, doesn't have any effect.

Latest Lynis on PCLinux.

**Comment by mboelen** [comment] 2022-05-04 09:58
It enables quick mode, which is by default enabled (in the default.prf). Previously it was not the default, so that is why it exists in the first place. For compatibility reasons, it is still available.

(closing issue as it is not a bug nor a change is suggested at this moment)

**Closed by mboelen** 2022-05-04 09:58 UTC
Labels: no-change
