### ISSUE TITLE
[test:HTTP-6660 warns that TraceEnable should be set to off, even though it is already off

### ISSUE THREAD

**Issue by lwt-pressy** [CISOfy/lynis#1543] opened 2024-09-27 07:40 UTC
**Describe the bug**
TraceEnable is set to "Off" and I would expect no warning

**Version**
 - Distribution [e.g. Ubuntu 18.04] Debian GNU/Linux 12 (bookworm)
 - Lynis version [e.g. 2.7.0] Lynis 3.1.2

**Expected behavior**
no warning

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

2024-09-27 09:34:08 Result: found TraceEnable setting set to 'Off' in /etc/apache2/conf-available/security.conf
2024-09-27 09:34:08 Suggestion: Consider setting 'TraceEnable Off' in /etc/apache2/conf-available/security.conf [test:HTTP-6660] [details:Set TraceEnable to 'On' or 'extended' for testing and diagnostic purposes only.] [solution:-]

**Additional context**

**Comment by mboelen** [comment] 2024-09-27 07:55
Can you show your relevant Apache configuration?

**Comment by lwt-pressy** [comment] 2024-09-27 08:05
`# cat security.conf
#
# Disable access to the entire file system except for the directories that
# are explicitly allowed later.
#
# This currently breaks the configurations that come with some web application
# Debian packages.
#
#<Directory />
#   AllowOverride None
#   Require all denied
#</Directory>


# Changing the following options will not really affect the security of the
# server, but might make attacks slightly more difficult in some cases.

#
# ServerTokens
# This directive configures what you return as the Server HTTP response
# Header. The default is 'Full' which sends information about the OS-Type
# and compiled in modules.
# Set to one of:  Full | OS | Minimal | Minor | Major | Prod
# where Full conveys the most information, and Prod the least.
#ServerTokens Minimal
#ServerTokens OS
#ServerTokens Full

#
# Optionally add a line containing the server version and virtual host
# name to server-generated pages (internal error documents, FTP directory
# listings, mod_status and mod_info output etc., but not CGI generated
# documents or custom error documents).
# Set to "EMail" to also include a mailto: link to the ServerAdmin.
# Set to one of:  On | Off | EMail
#ServerSignature Off
#ServerSignature On

#
# Allow TRACE method
#
# Set to "extended" to also reflect the request body (only for testing and
# diagnostic purposes).
#
# Set to one of:  On | Off | extended
TraceEnable Off
#TraceEnable On

#
# Forbid access to version control directories
#
# If you use version control systems in your document root, you should
# probably deny access to their directories. For example, for subversion:
#
#<DirectoryMatch "/\.svn">
#   Require all denied
#</DirectoryMatch>

#
# Setting this header will prevent MSIE from interpreting files as something
# else than declared by the content type in the HTTP headers.
# Requires mod_headers to be enabled.
#
#Header set X-Content-Type-Options: "nosniff"

#
# Setting this header will prevent other sites from embedding pages from this
# site as frames. This defends against clickjacking attacks.
# Requires mod_headers to be enabled.
#
#Header set X-Frame-Options: "sameorigin"


# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
`
in the normal output I just found, that could be related

`      /etc/apache2/sites-include/security.conf                [ NOT FOUND ]
      /etc/apache2/sites-include/security2.conf               [ NOT FOUND ]
/usr/sbin/lynis: 326: [: xoff: unexpected operator
      /etc/apache2/conf-enabled/security.conf                 [ SUGGESTION ]
`

**Comment by lwt-pressy** [comment] 2024-09-27 08:08
sorry for the format

**Comment by teoberi** [comment] 2024-09-27 08:33
It works for me but I only have in the configuration file:
`TraceEnable Off`
Delete line:
`#TraceEnable On`
to see if the message still appears!

**Comment by teoberi** [comment] 2024-09-27 09:51
Maybe related to:
https://github.com/CISOfy/lynis/pull/1536#issue-2497696487

**Comment by lwt-pressy** [comment] 2024-09-27 11:19
yes, if I temporary switch from dash to bash in /etc/sh everything works fine. Seems like bashism.

**Comment by teoberi** [comment] 2024-09-27 12:14
Check with patch above.

**Comment by RZR7332** [comment] 2024-09-27 12:42
I am seeing this on Ubuntu 24.04 as well, TraceEnable is set to Off.

Lynis also prints the line "_/usr/sbin/lynis: 326: [: xoff: unexpected operator_" three times during the Apache scan, not sure if this is related.

**Comment by RZR7332** [comment] 2024-09-29 09:42
> Maybe related to: [#1536 (comment)](https://github.com/CISOfy/lynis/pull/1536#issue-2497696487)

I can confirm the code changes in this PR resolve this.

**Comment by sigio** [comment] 2024-10-07 12:24
Same here, 3x /usr/sbin/lynis: 326: [: xoff: unexpected operator

Some redirected output:
```
628 ^[[4C  /etc/apache2/conf-available/localized-error-pages.conf^[[1C [ ^[[1;37mNOT FOUND^[[0m ]
629 ^[[4C  /etc/apache2/conf-available/other-vhosts-access-log.conf^[[0C [ ^[[1;37mNOT FOUND^[[0m ]
630 ^[[4C  /etc/apache2/conf-available/serve-cgi-bin.conf^[[9C [ ^[[1;37mNOT FOUND^[[0m ]
631 ^[[4C  /etc/apache2/conf-available/php8.2-fpm.conf^[[12C [ ^[[1;37mNOT FOUND^[[0m ]
632 /usr/sbin/lynis: 326: [: xoff: unexpected operator
633 ^[[4C  /etc/apache2/conf-available/security.conf^[[14C [ ^[[1;33mSUGGESTION^[[0m ]
634 ^[[4C  /etc/apache2/conf-available/charset.conf^[[15C [ ^[[1;37mNOT FOUND^[[0m ]
635 ^[[4C  /etc/apache2/conf-available/dehydrated.conf^[[12C [ ^[[1;37mNOT FOUND^[[0m ]
636 ^[[4C  /etc/apache2/conf-enabled/javascript-common.conf^[[7C [ ^[[1;37mNOT FOUND^[[0m ]
637 ^[[4C  /etc/apache2/conf-enabled/localized-error-pages.conf^[[3C [ ^[[1;37mNOT FOUND^[[0m ]
638 ^[[4C  /etc/apache2/conf-enabled/other-vhosts-access-log.conf^[[1C [ ^[[1;37mNOT FOUND^[[0m ]
639 ^[[4C  /etc/apache2/conf-enabled/serve-cgi-bin.conf^[[11C [ ^[[1;37mNOT FOUND^[[0m ]
640 ^[[4C  /etc/apache2/conf-enabled/php8.2-fpm.conf^[[14C [ ^[[1;37mNOT FOUND^[[0m ]
641 /usr/sbin/lynis: 326: [: xoff: unexpected operator
642 ^[[4C  /etc/apache2/conf-enabled/security.conf^[[16C [ ^[[1;33mSUGGESTION^[[0m ]
643 ^[[4C  /etc/apache2/conf-enabled/charset.conf^[[17C [ ^[[1;37mNOT FOUND^[[0m ]
644 ^[[4C  /etc/apache2/conf-enabled/dehydrated.conf^[[14C [ ^[[1;37mNOT FOUND^[[0m ]
645 ^[[4C  /etc/apache2/ports.conf^[[32C [ ^[[1;37mNOT FOUND^[[0m ]
646 /usr/sbin/lynis: 326: [: xoff: unexpected operator
647 ^[[4C  /etc/apache2/apache2.conf^[[30C [ ^[[1;33mSUGGESTION^[[0m ]
648 ^[[2C- Checking nginx^[[43C [ ^[[1;37mNOT FOUND^[[0m ]
```

And the occurances of TraceEnable:
```
root@XXX:/etc# ack TraceEnable
apache2/conf-available/security.conf
5:TraceEnable Off

apache2/apache2.conf
154:TraceEnable Off
```

**Comment by mboelen** [comment] 2024-10-08 09:02
Closing issue after merging #1536

**Closed by mboelen** 2024-10-08 09:02 UTC
Labels: information-needed
