### ISSUE TITLE
[CORE-1000] Binaries search and symbolic links

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#611] opened 2018-12-06 17:14 UTC
**Describe the bug**
During the CORE-1000 test, if Lynis finds symbolic links then Lynis does not use the binaries during the audit, which means that some tests fail while the binaries are present on the machine.

**Version**
 - Distribution : mandrake 2010
 - Lynis version 2.1.7

**Expected behavior**
Lynis should use binaries even if they are symbolic links

**Output**
```
FIND=$(ls -p ${SCANDIR} | grep -v '/$')
awk@
lsmod@
```

**Comment by mboelen** [comment] 2018-12-07 08:31
As you are using a very old version of Lynis, can you upgrade to the last one 2.7.0 and see if detection is improved?

**Comment by Capashenn** [comment] 2018-12-07 14:42
Excuse me, I was wrong when I wrote the lynis version.
I use version 2.7.1 for my tests.

**Comment by mboelen** [comment] 2019-07-12 18:45
I had a fresh look at this issue to see why ls would display a '@' at the first place. It looks like non-standard behavior. Do you still have this Mandrake system? Can you have a look if it uses an alias for ls?

**Comment by mboelen** [comment] 2019-08-23 04:50
Closing issue, as I can't reproduce it and as part of the work on the major release 3.x. Seems that on all modern Linux distributions the existing routine does work correctly, also when it encounters symlinks.

**Closed by mboelen** 2019-08-23 04:50 UTC
Labels: needs-confirmation
