### ISSUE TITLE
getting message "read: Illegal option -d" on Ubuntu hosts after upgrade to 2.5.4-1

### ISSUE THREAD

**Issue by shpokas** [CISOfy/lynis#460] opened 2017-09-07 08:19 UTC
After upgrade to 2.5.4-1 (which is now happening automatically, thanks) on Ubuntu hosts (but not on  Centos/RHEL) following messge appears:

# /usr/sbin/lynis audit system --plugin-dir /usr/share/lynis/plugins
...
[+] Cryptography
------------------------------------
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
  - Checking for expired SSL certificates                     [ NONE ]

[+] Virtualization
------------------------------------
...

I see this on all Ubuntu hosts with lynis installed and upgraded to 2.5.4-1.
Ubuntu version is "Ubuntu 16.04.3 LTS".

**Comment by mboelen** [comment] 2017-09-07 08:25
Duplicate of https://github.com/CISOfy/lynis/issues/458

Is already fixed, new version will be pushed out as soon as possible.

**Closed by mboelen** 2017-09-07 08:25 UTC
Labels: invalid
