### ISSUE TITLE
Nameserver check doesn't handle inline comments

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#638] opened 2019-02-07 23:08 UTC
**Describe the bug**
The nameserver check treats inline comments in /etc/resolv.conf as additional name servers.  Naturally, these don't resolve to anything.

**Version**
 - Distribution: Red Hat Enterprise Linux Server release 7.6 (Maipo
 - Lynis version: 2.7.1

**Expected behavior**
Anything after the pound sign/hash tag (#) should be ignored.

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

**Comment by mboelen** [comment] 2019-02-15 12:33
The resolv.conf (5) man page states that you should use a # as the first character, not somewhere else.

> Lines that contain a semicolon (;) or hash character (#) in the first column are treated as comments.

So considering this not a bug, but as incorrect usage of the resolv.conf file syntax. Will close this report for that reason.

**Closed by mboelen** 2019-02-15 12:33 UTC
Labels: wontfix
